### ISSUE TITLE
bredon-validate

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/bredon#25]
## Progress
Having **367** out of 446 properties.
Progress: **82.29%** done.

## ToDo
- [x] Split length/percentage validation
- [x] Automate keyword validation
- [x] Validate shorthand values
- [ ] value-set values
- [x] non-standard color names
- [ ] prefixed properties

## Missing properties
- [ ] MozContextProperties
- [ ] MozImageRegion
- [ ] MozOutlineRadius
- [ ] MozWindowDragging
- [ ] WebkitBorderBefore
- [ ] WebkitBoxReflect
- [ ] WebkitMask
- [ ] WebkitMaskImage
- [ ] WebkitMaskPosition
- [ ] WebkitMaskRepeat
- [ ] WebkitTextStroke
- [ ] animation
- [ ] azimuth
- [ ] backdropFilter
- [ ] background
- [ ] backgroundImage
- [ ] backgroundRepeat
- [ ] backgroundSize
- [ ] borderImage
- [ ] borderImageSlice
- [ ] borderImageSource
- [ ] boxShadow
- [ ] columnRule
- [ ] columns
- [ ] contain
- [ ] content
- [ ] counterIncrement
- [ ] counterReset
- [ ] filter
- [ ] font
- [ ] fontFeatureSettings
- [ ] fontLanguageOverride
- [ ] fontVariationSettings
- [ ] fontSynthesis
- [ ] fontVariantAlternates
- [ ] fontVariantEastAsian
- [ ] fontVariantLigatures
- [ ] fontVariantNumeric
- [ ] fontVariantPosition
- [ ] grid
- [ ] gridArea
- [ ] gridAutoColumns
- [ ] gridAutoFlow
- [ ] gridAutoRows
- [ ] gridColumn
- [ ] gridColumnEnd
- [ ] gridColumnGap
- [ ] gridColumnStart
- [ ] gridGap
- [ ] gridRow
- [ ] gridRowEnd
- [ ] gridRowGap
- [ ] gridRowStart
- [ ] gridTemplate
- [ ] gridTemplateAreas
- [ ] gridTemplateColumns
- [ ] gridTemplateRows
- [ ] hangingPunctuation
- [ ] imageOrientation
- [ ] imageResolution
- [ ] initialLetter
- [ ] lineHeightStep
- [ ] listStyle
- [ ] listStylePosition
- [ ] listStyleType
- [ ] mask
- [ ] maskBorder
- [ ] maskBorderSlice
- [ ] maskImage
- [ ] maskRepeat
- [ ] maskSize
- [ ] offset
- [ ] offsetPath
- [ ] offsetRotate
- [ ] outline
- [ ] overflowWrap
- [ ] shapeOutside
- [ ] textCombineUpright
- [ ] transform
